name: Build & Deploy Spring app

on: 
  push:
    branches:
      -main

jobs:
  build-deploy:
    name: Build and Deploy Spring boot for beginners
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with: 
          distidution: 'corretto'
          java-version: 17
          
      - name: Unit Test
        run: mvn -B test --file pom.xml

      - name: Buid the app
        run: |
          mvn clean 
          mvn - B package --file.pom.xml


          //this is my workflow





      